#!/bin/sh
set -e

case "$1" in
    install|configure)
        exampleConfig="/var/lib/linuxmuster-cachingserver/servers.json.example"
        realConfig="/var/lib/linuxmuster-cachingserver/servers.json"

        if [ ! -f $realConfig ]; then
            cp $exampleConfig $realConfig
        fi

        mkdir -p /var/log/linuxmuster/cachingserver/

        systemctl enable linuxmuster-cachingserver-server
        systemctl start linuxmuster-cachingserver-server

        mkdir -p /var/lib/linuxmuster/hooks/device-import.post.d
        ln -s /usr/lib/linuxmuster-cachingserver-server/helper_scripts/hook-executor-import-devices.sh /var/lib/linuxmuster/hooks/device-import.post.d/

        exit 0
        ;;
    upgrade|abort-upgrade)
        echo "No work to do..."
        exit 0
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0
