#!/bin/sh
set -e

case "$1" in
    install|configure)
        exampleConfig="/var/lib/linuxmuster-cachingserver/servers.json.example"
        realConfig="/var/lib/linuxmuster-cachingserver/servers.json"

        if [ ! -f $realConfig ]; then
            cp $exampleConfig $realConfig
        fi

        mkdir -p /var/log/linuxmuster/cachingserver/

        systemctl enable isc-dhcp-server
        systemctl enable tftpd-hpa
        systemctl enable rsync
        systemctl enable linuxmuster-cachingserver

        systemctl start tftpd-hpa
        systemctl start rsync
        systemctl start linuxmuster-cachingserver

        systemctl restart cron

        mkdir -p /var/lib/linuxmuster/hooks/device-import.post.d
        rm -f /var/lib/linuxmuster/hooks/device-import.post.d/hook-executor-import-devices.sh
        rm -f /var/lib/linuxmuster/hooks/device-import.post.d/hack-macct-to-ad.sh
        ln -s /usr/lib/linuxmuster-cachingserver/helper_scripts/hook-executor-import-devices.sh /var/lib/linuxmuster/hooks/device-import.post.d/
        ln -s /usr/lib/linuxmuster-cachingserver/helper_scripts/hack-macct-to-ad.sh /var/lib/linuxmuster/hooks/device-import.post.d/

        pip3 install fastapi -U
        pip3 install uvicorn

        exit 0
        ;;
    upgrade|abort-upgrade)
        echo "No work to do..."
        exit 0
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0
